# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import mess_pb2 as mess__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in mess_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """========== Services ==========

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateUser = channel.unary_unary(
                '/messenger.UserService/CreateUser',
                request_serializer=mess__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=mess__pb2.User.FromString,
                _registered_method=True)
        self.GetUser = channel.unary_unary(
                '/messenger.UserService/GetUser',
                request_serializer=mess__pb2.GetUserRequest.SerializeToString,
                response_deserializer=mess__pb2.User.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/messenger.UserService/UpdateUser',
                request_serializer=mess__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=mess__pb2.User.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/messenger.UserService/DeleteUser',
                request_serializer=mess__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.SearchUsers = channel.unary_unary(
                '/messenger.UserService/SearchUsers',
                request_serializer=mess__pb2.SearchUsersRequest.SerializeToString,
                response_deserializer=mess__pb2.UsersListResponse.FromString,
                _registered_method=True)
        self.GetMyProfile = channel.unary_unary(
                '/messenger.UserService/GetMyProfile',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=mess__pb2.User.FromString,
                _registered_method=True)
        self.UpdatePrivacy = channel.unary_unary(
                '/messenger.UserService/UpdatePrivacy',
                request_serializer=mess__pb2.UpdatePrivacyRequest.SerializeToString,
                response_deserializer=mess__pb2.PrivacySetting.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """========== Services ==========

    """

    def CreateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMyProfile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdatePrivacy(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=mess__pb2.CreateUserRequest.FromString,
                    response_serializer=mess__pb2.User.SerializeToString,
            ),
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=mess__pb2.GetUserRequest.FromString,
                    response_serializer=mess__pb2.User.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=mess__pb2.UpdateUserRequest.FromString,
                    response_serializer=mess__pb2.User.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=mess__pb2.DeleteUserRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'SearchUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchUsers,
                    request_deserializer=mess__pb2.SearchUsersRequest.FromString,
                    response_serializer=mess__pb2.UsersListResponse.SerializeToString,
            ),
            'GetMyProfile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMyProfile,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=mess__pb2.User.SerializeToString,
            ),
            'UpdatePrivacy': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdatePrivacy,
                    request_deserializer=mess__pb2.UpdatePrivacyRequest.FromString,
                    response_serializer=mess__pb2.PrivacySetting.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """========== Services ==========

    """

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/CreateUser',
            mess__pb2.CreateUserRequest.SerializeToString,
            mess__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/GetUser',
            mess__pb2.GetUserRequest.SerializeToString,
            mess__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/UpdateUser',
            mess__pb2.UpdateUserRequest.SerializeToString,
            mess__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/DeleteUser',
            mess__pb2.DeleteUserRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/SearchUsers',
            mess__pb2.SearchUsersRequest.SerializeToString,
            mess__pb2.UsersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMyProfile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/GetMyProfile',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            mess__pb2.User.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdatePrivacy(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.UserService/UpdatePrivacy',
            mess__pb2.UpdatePrivacyRequest.SerializeToString,
            mess__pb2.PrivacySetting.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Login = channel.unary_unary(
                '/messenger.AuthService/Login',
                request_serializer=mess__pb2.LoginRequest.SerializeToString,
                response_deserializer=mess__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/messenger.AuthService/Logout',
                request_serializer=mess__pb2.LogoutRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/messenger.AuthService/RefreshToken',
                request_serializer=mess__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=mess__pb2.LoginResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Login(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Login': grpc.unary_unary_rpc_method_handler(
                    servicer.Login,
                    request_deserializer=mess__pb2.LoginRequest.FromString,
                    response_serializer=mess__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=mess__pb2.LogoutRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=mess__pb2.RefreshTokenRequest.FromString,
                    response_serializer=mess__pb2.LoginResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Login(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.AuthService/Login',
            mess__pb2.LoginRequest.SerializeToString,
            mess__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.AuthService/Logout',
            mess__pb2.LogoutRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.AuthService/RefreshToken',
            mess__pb2.RefreshTokenRequest.SerializeToString,
            mess__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ContactServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddContact = channel.unary_unary(
                '/messenger.ContactService/AddContact',
                request_serializer=mess__pb2.AddContactRequest.SerializeToString,
                response_deserializer=mess__pb2.Contact.FromString,
                _registered_method=True)
        self.AcceptContact = channel.unary_unary(
                '/messenger.ContactService/AcceptContact',
                request_serializer=mess__pb2.AcceptContactRequest.SerializeToString,
                response_deserializer=mess__pb2.Contact.FromString,
                _registered_method=True)
        self.BlockContact = channel.unary_unary(
                '/messenger.ContactService/BlockContact',
                request_serializer=mess__pb2.BlockContactRequest.SerializeToString,
                response_deserializer=mess__pb2.Contact.FromString,
                _registered_method=True)
        self.RemoveContact = channel.unary_unary(
                '/messenger.ContactService/RemoveContact',
                request_serializer=mess__pb2.RemoveContactRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListContacts = channel.unary_unary(
                '/messenger.ContactService/ListContacts',
                request_serializer=mess__pb2.ListContactsRequest.SerializeToString,
                response_deserializer=mess__pb2.ContactsListResponse.FromString,
                _registered_method=True)


class ContactServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AddContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BlockContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveContact(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListContacts(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContactServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AddContact,
                    request_deserializer=mess__pb2.AddContactRequest.FromString,
                    response_serializer=mess__pb2.Contact.SerializeToString,
            ),
            'AcceptContact': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptContact,
                    request_deserializer=mess__pb2.AcceptContactRequest.FromString,
                    response_serializer=mess__pb2.Contact.SerializeToString,
            ),
            'BlockContact': grpc.unary_unary_rpc_method_handler(
                    servicer.BlockContact,
                    request_deserializer=mess__pb2.BlockContactRequest.FromString,
                    response_serializer=mess__pb2.Contact.SerializeToString,
            ),
            'RemoveContact': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveContact,
                    request_deserializer=mess__pb2.RemoveContactRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListContacts': grpc.unary_unary_rpc_method_handler(
                    servicer.ListContacts,
                    request_deserializer=mess__pb2.ListContactsRequest.FromString,
                    response_serializer=mess__pb2.ContactsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.ContactService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.ContactService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContactService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AddContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ContactService/AddContact',
            mess__pb2.AddContactRequest.SerializeToString,
            mess__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ContactService/AcceptContact',
            mess__pb2.AcceptContactRequest.SerializeToString,
            mess__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BlockContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ContactService/BlockContact',
            mess__pb2.BlockContactRequest.SerializeToString,
            mess__pb2.Contact.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveContact(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ContactService/RemoveContact',
            mess__pb2.RemoveContactRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListContacts(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ContactService/ListContacts',
            mess__pb2.ListContactsRequest.SerializeToString,
            mess__pb2.ContactsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChatServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateChat = channel.unary_unary(
                '/messenger.ChatService/CreateChat',
                request_serializer=mess__pb2.CreateChatRequest.SerializeToString,
                response_deserializer=mess__pb2.Chat.FromString,
                _registered_method=True)
        self.GetChat = channel.unary_unary(
                '/messenger.ChatService/GetChat',
                request_serializer=mess__pb2.GetChatRequest.SerializeToString,
                response_deserializer=mess__pb2.Chat.FromString,
                _registered_method=True)
        self.UpdateChat = channel.unary_unary(
                '/messenger.ChatService/UpdateChat',
                request_serializer=mess__pb2.UpdateChatRequest.SerializeToString,
                response_deserializer=mess__pb2.Chat.FromString,
                _registered_method=True)
        self.DeleteChat = channel.unary_unary(
                '/messenger.ChatService/DeleteChat',
                request_serializer=mess__pb2.DeleteChatRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListChats = channel.unary_unary(
                '/messenger.ChatService/ListChats',
                request_serializer=mess__pb2.ListChatsRequest.SerializeToString,
                response_deserializer=mess__pb2.ChatsListResponse.FromString,
                _registered_method=True)
        self.AddChatMember = channel.unary_unary(
                '/messenger.ChatService/AddChatMember',
                request_serializer=mess__pb2.AddChatMemberRequest.SerializeToString,
                response_deserializer=mess__pb2.ChatMember.FromString,
                _registered_method=True)
        self.UpdateChatMember = channel.unary_unary(
                '/messenger.ChatService/UpdateChatMember',
                request_serializer=mess__pb2.UpdateChatMemberRequest.SerializeToString,
                response_deserializer=mess__pb2.ChatMember.FromString,
                _registered_method=True)
        self.RemoveChatMember = channel.unary_unary(
                '/messenger.ChatService/RemoveChatMember',
                request_serializer=mess__pb2.RemoveChatMemberRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListChatMembers = channel.unary_unary(
                '/messenger.ChatService/ListChatMembers',
                request_serializer=mess__pb2.ListChatMembersRequest.SerializeToString,
                response_deserializer=mess__pb2.ChatMembersListResponse.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteChat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddChatMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateChatMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveChatMember(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListChatMembers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateChat,
                    request_deserializer=mess__pb2.CreateChatRequest.FromString,
                    response_serializer=mess__pb2.Chat.SerializeToString,
            ),
            'GetChat': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChat,
                    request_deserializer=mess__pb2.GetChatRequest.FromString,
                    response_serializer=mess__pb2.Chat.SerializeToString,
            ),
            'UpdateChat': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChat,
                    request_deserializer=mess__pb2.UpdateChatRequest.FromString,
                    response_serializer=mess__pb2.Chat.SerializeToString,
            ),
            'DeleteChat': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteChat,
                    request_deserializer=mess__pb2.DeleteChatRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListChats': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChats,
                    request_deserializer=mess__pb2.ListChatsRequest.FromString,
                    response_serializer=mess__pb2.ChatsListResponse.SerializeToString,
            ),
            'AddChatMember': grpc.unary_unary_rpc_method_handler(
                    servicer.AddChatMember,
                    request_deserializer=mess__pb2.AddChatMemberRequest.FromString,
                    response_serializer=mess__pb2.ChatMember.SerializeToString,
            ),
            'UpdateChatMember': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateChatMember,
                    request_deserializer=mess__pb2.UpdateChatMemberRequest.FromString,
                    response_serializer=mess__pb2.ChatMember.SerializeToString,
            ),
            'RemoveChatMember': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveChatMember,
                    request_deserializer=mess__pb2.RemoveChatMemberRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListChatMembers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListChatMembers,
                    request_deserializer=mess__pb2.ListChatMembersRequest.FromString,
                    response_serializer=mess__pb2.ChatMembersListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/CreateChat',
            mess__pb2.CreateChatRequest.SerializeToString,
            mess__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/GetChat',
            mess__pb2.GetChatRequest.SerializeToString,
            mess__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/UpdateChat',
            mess__pb2.UpdateChatRequest.SerializeToString,
            mess__pb2.Chat.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteChat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/DeleteChat',
            mess__pb2.DeleteChatRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/ListChats',
            mess__pb2.ListChatsRequest.SerializeToString,
            mess__pb2.ChatsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddChatMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/AddChatMember',
            mess__pb2.AddChatMemberRequest.SerializeToString,
            mess__pb2.ChatMember.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateChatMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/UpdateChatMember',
            mess__pb2.UpdateChatMemberRequest.SerializeToString,
            mess__pb2.ChatMember.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveChatMember(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/RemoveChatMember',
            mess__pb2.RemoveChatMemberRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListChatMembers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.ChatService/ListChatMembers',
            mess__pb2.ListChatMembersRequest.SerializeToString,
            mess__pb2.ChatMembersListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class MessageServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/messenger.MessageService/SendMessage',
                request_serializer=mess__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=mess__pb2.Message.FromString,
                _registered_method=True)
        self.GetMessage = channel.unary_unary(
                '/messenger.MessageService/GetMessage',
                request_serializer=mess__pb2.GetMessageRequest.SerializeToString,
                response_deserializer=mess__pb2.Message.FromString,
                _registered_method=True)
        self.UpdateMessage = channel.unary_unary(
                '/messenger.MessageService/UpdateMessage',
                request_serializer=mess__pb2.UpdateMessageRequest.SerializeToString,
                response_deserializer=mess__pb2.Message.FromString,
                _registered_method=True)
        self.DeleteMessage = channel.unary_unary(
                '/messenger.MessageService/DeleteMessage',
                request_serializer=mess__pb2.DeleteMessageRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.ListMessages = channel.unary_unary(
                '/messenger.MessageService/ListMessages',
                request_serializer=mess__pb2.ListMessagesRequest.SerializeToString,
                response_deserializer=mess__pb2.MessagesListResponse.FromString,
                _registered_method=True)
        self.AddReaction = channel.unary_unary(
                '/messenger.MessageService/AddReaction',
                request_serializer=mess__pb2.AddReactionRequest.SerializeToString,
                response_deserializer=mess__pb2.Reaction.FromString,
                _registered_method=True)
        self.RemoveReaction = channel.unary_unary(
                '/messenger.MessageService/RemoveReaction',
                request_serializer=mess__pb2.RemoveReactionRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetMessageStatus = channel.unary_unary(
                '/messenger.MessageService/GetMessageStatus',
                request_serializer=mess__pb2.GetMessageStatusRequest.SerializeToString,
                response_deserializer=mess__pb2.MessageStatusResponse.FromString,
                _registered_method=True)
        self.StreamMessages = channel.unary_stream(
                '/messenger.MessageService/StreamMessages',
                request_serializer=mess__pb2.StreamMessagesRequest.SerializeToString,
                response_deserializer=mess__pb2.MessageEvent.FromString,
                _registered_method=True)


class MessageServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveReaction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessageStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamMessages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=mess__pb2.SendMessageRequest.FromString,
                    response_serializer=mess__pb2.Message.SerializeToString,
            ),
            'GetMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessage,
                    request_deserializer=mess__pb2.GetMessageRequest.FromString,
                    response_serializer=mess__pb2.Message.SerializeToString,
            ),
            'UpdateMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMessage,
                    request_deserializer=mess__pb2.UpdateMessageRequest.FromString,
                    response_serializer=mess__pb2.Message.SerializeToString,
            ),
            'DeleteMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMessage,
                    request_deserializer=mess__pb2.DeleteMessageRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'ListMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListMessages,
                    request_deserializer=mess__pb2.ListMessagesRequest.FromString,
                    response_serializer=mess__pb2.MessagesListResponse.SerializeToString,
            ),
            'AddReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.AddReaction,
                    request_deserializer=mess__pb2.AddReactionRequest.FromString,
                    response_serializer=mess__pb2.Reaction.SerializeToString,
            ),
            'RemoveReaction': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveReaction,
                    request_deserializer=mess__pb2.RemoveReactionRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetMessageStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessageStatus,
                    request_deserializer=mess__pb2.GetMessageStatusRequest.FromString,
                    response_serializer=mess__pb2.MessageStatusResponse.SerializeToString,
            ),
            'StreamMessages': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamMessages,
                    request_deserializer=mess__pb2.StreamMessagesRequest.FromString,
                    response_serializer=mess__pb2.MessageEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.MessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.MessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MessageService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/SendMessage',
            mess__pb2.SendMessageRequest.SerializeToString,
            mess__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/GetMessage',
            mess__pb2.GetMessageRequest.SerializeToString,
            mess__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/UpdateMessage',
            mess__pb2.UpdateMessageRequest.SerializeToString,
            mess__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/DeleteMessage',
            mess__pb2.DeleteMessageRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/ListMessages',
            mess__pb2.ListMessagesRequest.SerializeToString,
            mess__pb2.MessagesListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/AddReaction',
            mess__pb2.AddReactionRequest.SerializeToString,
            mess__pb2.Reaction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveReaction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/RemoveReaction',
            mess__pb2.RemoveReactionRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessageStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.MessageService/GetMessageStatus',
            mess__pb2.GetMessageStatusRequest.SerializeToString,
            mess__pb2.MessageStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/messenger.MessageService/StreamMessages',
            mess__pb2.StreamMessagesRequest.SerializeToString,
            mess__pb2.MessageEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class AttachmentServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadAttachment = channel.stream_unary(
                '/messenger.AttachmentService/UploadAttachment',
                request_serializer=mess__pb2.UploadAttachmentRequest.SerializeToString,
                response_deserializer=mess__pb2.UploadAttachmentResponse.FromString,
                _registered_method=True)
        self.GetAttachment = channel.unary_unary(
                '/messenger.AttachmentService/GetAttachment',
                request_serializer=mess__pb2.GetAttachmentRequest.SerializeToString,
                response_deserializer=mess__pb2.Attachment.FromString,
                _registered_method=True)
        self.ListAttachments = channel.unary_unary(
                '/messenger.AttachmentService/ListAttachments',
                request_serializer=mess__pb2.ListAttachmentsRequest.SerializeToString,
                response_deserializer=mess__pb2.AttachmentsListResponse.FromString,
                _registered_method=True)


class AttachmentServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadAttachment(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAttachment(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListAttachments(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AttachmentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadAttachment': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadAttachment,
                    request_deserializer=mess__pb2.UploadAttachmentRequest.FromString,
                    response_serializer=mess__pb2.UploadAttachmentResponse.SerializeToString,
            ),
            'GetAttachment': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAttachment,
                    request_deserializer=mess__pb2.GetAttachmentRequest.FromString,
                    response_serializer=mess__pb2.Attachment.SerializeToString,
            ),
            'ListAttachments': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAttachments,
                    request_deserializer=mess__pb2.ListAttachmentsRequest.FromString,
                    response_serializer=mess__pb2.AttachmentsListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.AttachmentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.AttachmentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AttachmentService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadAttachment(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/messenger.AttachmentService/UploadAttachment',
            mess__pb2.UploadAttachmentRequest.SerializeToString,
            mess__pb2.UploadAttachmentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAttachment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.AttachmentService/GetAttachment',
            mess__pb2.GetAttachmentRequest.SerializeToString,
            mess__pb2.Attachment.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListAttachments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.AttachmentService/ListAttachments',
            mess__pb2.ListAttachmentsRequest.SerializeToString,
            mess__pb2.AttachmentsListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class EmojiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListEmojis = channel.unary_unary(
                '/messenger.EmojiService/ListEmojis',
                request_serializer=mess__pb2.ListEmojisRequest.SerializeToString,
                response_deserializer=mess__pb2.EmojisListResponse.FromString,
                _registered_method=True)
        self.SearchEmojis = channel.unary_unary(
                '/messenger.EmojiService/SearchEmojis',
                request_serializer=mess__pb2.SearchEmojisRequest.SerializeToString,
                response_deserializer=mess__pb2.EmojisListResponse.FromString,
                _registered_method=True)


class EmojiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListEmojis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchEmojis(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_EmojiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListEmojis': grpc.unary_unary_rpc_method_handler(
                    servicer.ListEmojis,
                    request_deserializer=mess__pb2.ListEmojisRequest.FromString,
                    response_serializer=mess__pb2.EmojisListResponse.SerializeToString,
            ),
            'SearchEmojis': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchEmojis,
                    request_deserializer=mess__pb2.SearchEmojisRequest.FromString,
                    response_serializer=mess__pb2.EmojisListResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'messenger.EmojiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('messenger.EmojiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class EmojiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListEmojis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.EmojiService/ListEmojis',
            mess__pb2.ListEmojisRequest.SerializeToString,
            mess__pb2.EmojisListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchEmojis(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/messenger.EmojiService/SearchEmojis',
            mess__pb2.SearchEmojisRequest.SerializeToString,
            mess__pb2.EmojisListResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
