"""Initial schema

Revision ID: fdf1873a3499
Revises: 
Create Date: 2026-02-18 11:03:43.006464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fdf1873a3499'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text('CREATE EXTENSION IF NOT EXISTS pg_trgm'))

    op.create_table('emoji',
    sa.Column('emoji_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code_point', sa.Text(), nullable=False),
    sa.Column('character', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('category', sa.Text(), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('emoji_id'),
    sa.UniqueConstraint('code_point')
    )
    op.create_index('idx_emoji_keywords', 'emoji', ['keywords'], unique=False, postgresql_using='gin')
    op.create_index('idx_emoji_name_trgm', 'emoji', ['name'], unique=False, postgresql_using='gin',postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nick_name', sa.String(length=50), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('salt', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('last_seen', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('active', 'suspended', 'deleted', name='account_status'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nick_name'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id', 'created_at')
    )
    op.create_index('idx_audit_details', 'audit_logs', ['details'], unique=False, postgresql_using='gin')
    op.create_table('chats',
    sa.Column('chat_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('chat_type', sa.Enum('private', 'group', 'channel', name='chat_type'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('chat_id')
    )
    op.create_table('contacts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', 'blocked', name='contact_status'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('user_id <> contact_user_id', name='no_self_contact'),
    sa.ForeignKeyConstraint(['contact_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'contact_user_id')
    )
    op.create_table('privacy_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('who_can_write_me', sa.Enum('everyone', 'contacts', 'nobody', name='privacy_level'), nullable=False),
    sa.Column('who_can_add_to_groups', sa.Enum('everyone', 'contacts', 'nobody', name='privacy_level'), nullable=False),
    sa.Column('who_can_see_phone', sa.Enum('everyone', 'contacts', 'nobody', name='privacy_level'), nullable=False),
    sa.Column('who_can_see_last_seen', sa.Enum('everyone', 'contacts', 'nobody', name='privacy_level'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('session_events',
    sa.Column('event_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('refresh_token_hash', sa.Text(), nullable=True),
    sa.Column('device_info', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'created_at')
    )
    op.create_table('chat_members',
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', name='member_role'), nullable=False),
    sa.Column('status', sa.Enum('active', 'left', 'banned', name='member_status'), nullable=False),
    sa.Column('joined_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('banned_until', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chat_id', 'user_id')
    )
    op.create_table('messages',
    sa.Column('message_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('reply_to_id', sa.BigInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('encrypted_content', sa.LargeBinary(), nullable=True),
    sa.Column('type', sa.Enum('text', 'image', 'video', 'audio', 'file', 'location', 'contact', 'mixed', name='message_type'), nullable=False),
    sa.Column('message_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'created_at')
    )
    op.create_index('idx_messages_chat_created', 'messages', ['chat_id', 'created_at'], unique=False)
    op.create_index('idx_messages_metadata', 'messages', ['message_metadata'], unique=False, postgresql_using='gin')
    op.create_index('idx_messages_sender', 'messages', ['sender_id'], unique=False)
    op.create_table('attachments',
    sa.Column('attachment_id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('file_name', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id', 'message_created_at'], ['messages.message_id', 'messages.created_at'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attachment_id')
    )
    op.create_table('mentions',
    sa.Column('mention_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('mentioned_user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mentioned_user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id', 'message_created_at'], ['messages.message_id', 'messages.created_at'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('mention_id'),
    sa.UniqueConstraint('message_id', 'mentioned_user_id')
    )
    op.create_table('message_statuses',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('delivered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('read_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['message_id', 'message_created_at'], ['messages.message_id', 'messages.created_at'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id')
    )
    op.create_index('idx_message_statuses_unread', 'message_statuses', ['user_id', 'message_id'], unique=False, postgresql_where=sa.text('read_at IS NULL'))
    op.create_table('reactions',
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('message_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('emoji', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['message_id', 'message_created_at'], ['messages.message_id', 'messages.created_at'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id', 'user_id', 'emoji')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reactions')
    op.drop_index('idx_message_statuses_unread', table_name='message_statuses', postgresql_where=sa.text('read_at IS NULL'))
    op.drop_table('message_statuses')
    op.drop_table('mentions')
    op.drop_table('attachments')
    op.drop_index('idx_messages_sender', table_name='messages')
    op.drop_index('idx_messages_metadata', table_name='messages', postgresql_using='gin')
    op.drop_index('idx_messages_chat_created', table_name='messages')
    op.drop_table('messages')
    op.drop_table('chat_members')
    op.drop_table('session_events')
    op.drop_table('privacy_settings')
    op.drop_table('contacts')
    op.drop_table('chats')
    op.drop_index('idx_audit_details', table_name='audit_logs', postgresql_using='gin')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_index('idx_emoji_name_trgm', table_name='emoji', postgresql_using='gin')
    op.drop_index('idx_emoji_keywords', table_name='emoji', postgresql_using='gin')
    op.drop_table('emoji')
    # ### end Alembic commands ###
